import React, { useState, useEffect, useCallback } from 'react';
import { fetchPredictiveInsights } from '../services/geminiService';
import { trackAiInsightView } from '../services/analyticsService';
import { Brain, Zap, RefreshCw, CheckCircle } from 'lucide-react';

/**
 * GeminiInsights Component
 *
 * Displays real-time AI-powered crowd management insights generated by
 * Google Gemini 1.5 Flash. Includes a backend-driven TTL cache indicator
 * and manual refresh capability.
 *
 * @component
 * @returns {JSX.Element}
 */
const GeminiInsights = () => {
  const [insight, setInsight] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [isCached, setIsCached] = useState(false);

  const loadInsights = useCallback(async () => {
    setLoading(true);
    setError(null);
    const result = await fetchPredictiveInsights();
    if (result.success) {
      setInsight(result.prediction);
      setIsCached(result.cached);
      trackAiInsightView(result.cached, result.prediction?.confidenceScore);
    } else {
      setError(result.error);
    }
    setLoading(false);
  }, []);

  useEffect(() => {
    loadInsights();
  }, [loadInsights]);

  return (
    <section
      className="glass-card animate-in gemini-card"
      style={{ animationDelay: '0.4s' }}
      aria-labelledby="gemini-title"
    >
      <div className="gemini-header">
        <h3 id="gemini-title" className="gemini-title">
          <Brain size={20} aria-hidden="true" className="gemini-icon" />
          Gemini AI Crowd Intelligence
        </h3>
        <div className="gemini-header-actions">
          {isCached && (
            <span className="gemini-cache-badge" aria-label="Result served from cache">
              <CheckCircle size={12} aria-hidden="true" /> Cached
            </span>
          )}
          <button
            onClick={loadInsights}
            disabled={loading}
            aria-label={loading ? 'Refreshing AI insights' : 'Refresh AI insights'}
            className="gemini-refresh-btn"
          >
            <RefreshCw size={14} className={loading ? 'spin' : ''} aria-hidden="true" />
          </button>
        </div>
      </div>

      <div aria-live="polite" aria-atomic="true">
        {loading && (
          <div className="gemini-loading">
            <div className="gemini-spinner" role="status" aria-label="Loading AI insights">
              <div className="spinner-ring" />
            </div>
            <p className="gemini-loading-text">Analyzing live crowd data with Gemini...</p>
          </div>
        )}

        {error && !loading && (
          <div className="gemini-error" role="alert">
            <p>{error}</p>
          </div>
        )}

        {insight && !loading && (
          <div className="gemini-results">
            <div className="gemini-insight-block">
              <div className="gemini-label">
                <Zap size={14} aria-hidden="true" />
                Predictive Insight
              </div>
              <p className="gemini-insight-text">{insight.insight}</p>
            </div>
            <div className="gemini-insight-block">
              <div className="gemini-label">
                <Zap size={14} aria-hidden="true" />
                Staff Recommendation
              </div>
              <p className="gemini-insight-text">{insight.recommendation}</p>
            </div>
            <div className="gemini-confidence">
              <div className="gemini-confidence-label">
                Model Confidence
              </div>
              <div
                className="gemini-confidence-bar-track"
                role="progressbar"
                aria-valuenow={Math.round((insight.confidenceScore ?? 0) * 100)}
                aria-valuemin={0}
                aria-valuemax={100}
                aria-label={`Model confidence: ${Math.round((insight.confidenceScore ?? 0) * 100)}%`}
              >
                <div
                  className="gemini-confidence-bar-fill"
                  style={{ width: `${Math.round((insight.confidenceScore ?? 0) * 100)}%` }}
                />
              </div>
              <span className="gemini-confidence-value">
                {Math.round((insight.confidenceScore ?? 0) * 100)}%
              </span>
            </div>
          </div>
        )}
      </div>

      <p className="gemini-footer">
        Powered by <strong>Google Gemini 1.5 Flash</strong> · Auto-refreshes every 5 minutes
      </p>
    </section>
  );
};

export default GeminiInsights;
